[package]
name = "it"
publish = false
version.workspace = true
license.workspace = true
edition = "2024"

[features]
integration = ["dep:testcontainers", "dep:rustls"]

[dependencies]
tokio = { workspace = true }
anyhow = { workspace = true }
reqwest = { workspace = true }
exarrow-rs = { workspace = true }
arrow = { workspace = true }
testcontainers = { workspace = true, optional = true }
rustls = { version = "0.23", default-features = false, features = ["aws_lc_rs"], optional = true }
